package com.paymentplaform.raya.gate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-11-08T12:21:38.189+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://raya.paymentplaform.com/gate", name = "GatePort")
@XmlSeeAlso({com.paymentplaform.raya.gate.search.ObjectFactory.class, com.paymentplaform.raya.gate.change.ObjectFactory.class, com.paymentplaform.raya.gate.activate.ObjectFactory.class, com.paymentplaform.raya.gate.rev.ObjectFactory.class, com.paymentplaform.raya.gate.summary.ObjectFactory.class, com.paymentplaform.raya.gate.pagservice.ObjectFactory.class, com.paymentplaform.raya.gate.init.ObjectFactory.class, com.paymentplaform.raya.gate.services.ObjectFactory.class, ObjectFactory.class, com.paymentplaform.raya.gate.inq.ObjectFactory.class, com.paymentplaform.raya.gate.fee.ObjectFactory.class, com.paymentplaform.raya.gate.distack.ObjectFactory.class, com.paymentplaform.raya.gate.balance.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GatePort {

    @WebResult(name = "LoadSDPaginationResponse", targetNamespace = "http://raya.paymentplaform.com/gate/pagservice", partName = "LoadSDPaginationResponse")
    @WebMethod(operationName = "ServiceDirectoryPagination", action = "http://raya.paymentplaform.com/pagservice")
    public com.paymentplaform.raya.gate.pagservice.LoadSDPaginationResponse serviceDirectoryPagination(
        @WebParam(partName = "LoadSDPaginationRequest", name = "LoadSDPaginationReq", targetNamespace = "http://raya.paymentplaform.com/gate/pagservice")
        com.paymentplaform.raya.gate.pagservice.LoadSDPaginationReq loadSDPaginationRequest
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "ReversePayment", action = "http://raya.paymentplaform.com/ReversePayment")
    public com.paymentplaform.raya.gate.rev.ReversePaymentResponseType reversePayment(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/rev")
        com.paymentplaform.raya.gate.rev.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/rev")
        com.paymentplaform.raya.gate.rev.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "Activate", action = "http://raya.paymentplaform.com/Activate")
    public com.paymentplaform.raya.gate.activate.ActivateResponseType activate(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/activate")
        com.paymentplaform.raya.gate.activate.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/activate")
        com.paymentplaform.raya.gate.activate.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "InitPayment", action = "http://raya.paymentplaform.com/InitPayment")
    public com.paymentplaform.raya.gate.init.InitPaymentResponseType initPayment(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/init")
        com.paymentplaform.raya.gate.init.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/init")
        com.paymentplaform.raya.gate.init.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "BillsInquiry", action = "http://raya.paymentplaform.com/BillsInquiry")
    public com.paymentplaform.raya.gate.inq.BillsInquiryResponseType billsInquiry(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/inq")
        com.paymentplaform.raya.gate.inq.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/inq")
        com.paymentplaform.raya.gate.inq.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "DailySummaryInquiry", action = "http://raya.paymentplaform.com/DailySummaryInquiry")
    public com.paymentplaform.raya.gate.summary.DailySummaryResponseType dailySummaryInquiry(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/summary")
        com.paymentplaform.raya.gate.summary.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/summary")
        com.paymentplaform.raya.gate.summary.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "VoucherDistack", action = "http://raya.paymentplaform.com/VoucherDistack")
    public com.paymentplaform.raya.gate.distack.ConfirmVoucherPrintResponseType voucherDistack(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/distack")
        com.paymentplaform.raya.gate.distack.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/distack")
        com.paymentplaform.raya.gate.distack.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "ChangeProfile", action = "http://raya.paymentplaform.com/ChangeProfile")
    public com.paymentplaform.raya.gate.change.ChangeProfileResponseType changeProfile(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/change")
        com.paymentplaform.raya.gate.change.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/change")
        com.paymentplaform.raya.gate.change.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "CalculateFee", action = "http://raya.paymentplaform.com/Fee")
    public com.paymentplaform.raya.gate.fee.FeeResponseType calculateFee(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/fee")
        com.paymentplaform.raya.gate.fee.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/fee")
        com.paymentplaform.raya.gate.fee.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "SearchTransactions", action = "http://raya.paymentplaform.com/SearchTransactions")
    public com.paymentplaform.raya.gate.search.SearchTransactionsResponseType searchTransactions(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/search")
        com.paymentplaform.raya.gate.search.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/search")
        com.paymentplaform.raya.gate.search.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "MessageBody", targetNamespace = "", partName = "MessageBody")
    @WebMethod(operationName = "InquireBalance", action = "http://raya.paymentplaform.com/InquireBalance")
    public com.paymentplaform.raya.gate.balance.InquiryBalanceResponseType inquireBalance(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://raya.paymentplaform.com/gate/balance")
        com.paymentplaform.raya.gate.balance.MessageHeader messageHeader,
        @WebParam(partName = "MessageBody", name = "MessageBody", targetNamespace = "http://raya.paymentplaform.com/gate/balance")
        com.paymentplaform.raya.gate.balance.MessageBody messageBody
    ) throws TimeoutException, RemoteNotAvailableException;

    @WebResult(name = "LoadServiceDirectoryResponse", targetNamespace = "http://raya.paymentplaform.com/gate/services/", partName = "LoadServiceDirectoryResponse")
    @WebMethod(operationName = "ServiceDirectory", action = "http://raya.paymentplaform.com/ServiceDirectory")
    public com.paymentplaform.raya.gate.services.LoadServiceDirectoryResponse serviceDirectory(
        @WebParam(partName = "LoadServiceDirectoryRequest", name = "LoadServiceDirectoryReq", targetNamespace = "http://raya.paymentplaform.com/gate/services/")
        com.paymentplaform.raya.gate.services.LoadServiceDirectoryReq loadServiceDirectoryRequest
    ) throws TimeoutException, RemoteNotAvailableException;
}
