
package com.paymentplaform.raya.gate;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-11-08T12:21:38.181+02:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "RemoteNotAvailableFault", targetNamespace = "http://raya.paymentplaform.com/gate")
public class RemoteNotAvailableException extends Exception {
    
    private com.paymentplaform.raya.gate.RemoteNotAvailableFault remoteNotAvailableFault;

    public RemoteNotAvailableException() {
        super();
    }
    
    public RemoteNotAvailableException(String message) {
        super(message);
    }
    
    public RemoteNotAvailableException(String message, Throwable cause) {
        super(message, cause);
    }

    public RemoteNotAvailableException(String message, com.paymentplaform.raya.gate.RemoteNotAvailableFault remoteNotAvailableFault) {
        super(message);
        this.remoteNotAvailableFault = remoteNotAvailableFault;
    }

    public RemoteNotAvailableException(String message, com.paymentplaform.raya.gate.RemoteNotAvailableFault remoteNotAvailableFault, Throwable cause) {
        super(message, cause);
        this.remoteNotAvailableFault = remoteNotAvailableFault;
    }

    public com.paymentplaform.raya.gate.RemoteNotAvailableFault getFaultInfo() {
        return this.remoteNotAvailableFault;
    }
}
