
package com.paymentplaform.raya.gate;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-11-08T12:21:38.129+02:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "TimeoutFault", targetNamespace = "http://raya.paymentplaform.com/gate")
public class TimeoutException extends Exception {
    
    private com.paymentplaform.raya.gate.TimeoutFault timeoutFault;

    public TimeoutException() {
        super();
    }
    
    public TimeoutException(String message) {
        super(message);
    }
    
    public TimeoutException(String message, Throwable cause) {
        super(message, cause);
    }

    public TimeoutException(String message, com.paymentplaform.raya.gate.TimeoutFault timeoutFault) {
        super(message);
        this.timeoutFault = timeoutFault;
    }

    public TimeoutException(String message, com.paymentplaform.raya.gate.TimeoutFault timeoutFault, Throwable cause) {
        super(message, cause);
        this.timeoutFault = timeoutFault;
    }

    public com.paymentplaform.raya.gate.TimeoutFault getFaultInfo() {
        return this.timeoutFault;
    }
}
